url: https://phothinmg.github.io/
baseurl: /jekyll-tabler
title: Jekyll Tabler
markdown: kramdown
source: docs
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sidebar:
  - text: Home
    link: /
  - text: Filled
    link: /filled
